[package]
name = "win-toast-sys"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2021"

[build-dependencies]
bindgen = "0.69"
cc = "1"
cmake = "0.1"

[dev-dependencies]
lazy_static = "1"
