[package]
name = "win-toast-sys"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[build-dependencies]
bindgen = "0.59"
cc = "1"

[dev-dependencies]
lazy_static = "1"
