[package]
name = "rust-win-toast"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2.67"

[build-dependencies]
bindgen = "0.53.1"
cc = "1.0.50"
